services:
  spotiflac:
    build: .  # <--- EKSİK OLAN SİHİRLİ SATIR BURASI (Noktayı unutma)
    image: spotiflac-server:latest
    container_name: spotiflac-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /root/runtipi/runtipi/media/music:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul