services:
  spotiflac-server:
    build: .
    container_name: spotiflac-server
    ports:
      - "5000:5000"
    volumes:
      # İndirilenlerin Navidrome'un okuduğu Runtipi medya klasörüne düşmesi için:
      - /root/runtipi/runtipi/media/music:/downloads
    restart: unless-stopped